cmake_minimum_required(VERSION 3.10)

set(UA_ENABLE_AMALGAMATION ON CACHE BOOL "")
set(UA_ENABLE_NONSTANDARD_STATELESS ON CACHE BOOL "")
set(UA_ENABLE_NONSTANDARD_UDP ON CACHE BOOL "")
set( ON CACHE BOOL "")
set( ON CACHE BOOL "")

include(${CGET_CMAKE_ORIGINAL_SOURCE_FILE})
install(FILES ${PROJECT_BINARY_DIR}/open62541.c DESTINATION include)
